import { GoogleGenerativeAI } from "@google/generative-ai";
import { BaseProvider, LLMResponse } from "../core/types.js";

export class GeminiProvider implements BaseProvider {
  private client: GoogleGenerativeAI;
  private model: any;

  constructor(apiKey: string, modelName: string = "gemini-2.0-flash", systemInstruction?: string) {
    this.client = new GoogleGenerativeAI(apiKey);
    const modelOptions: any = { model: modelName };
    if (systemInstruction) {
      modelOptions.systemInstruction = systemInstruction;
    }
    this.model = this.client.getGenerativeModel(modelOptions);
  }

  async chat(messages: any[], tools?: any[]): Promise<LLMResponse> {
    const config: any = { contents: messages };
    if (tools && tools.length > 0) {
      config.tools = [{ functionDeclarations: tools }];
    }

    try {
      const result = await this.model.generateContent(config);
      return this.parseResponse(result);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : String(err);
      return {
        content: `Error calling Gemini API: ${errorMessage}`,
        toolCalls: undefined
      };
    }
  }

  private parseResponse(result: any): LLMResponse {
    let text = "";
    try {
      // Access candidates directly to check for safety blocks/refusals
      const response = result.response;
      if (response.candidates && response.candidates.length > 0) {
        const candidate = response.candidates[0];
        if (candidate.content && candidate.content.parts && candidate.content.parts.length > 0) {
          text = candidate.content.parts[0].text || "";
        } else if (candidate.finishReason === 'SAFETY') {
          text = "I'm sorry, I cannot respond to that due to safety policies.";
        } else if (candidate.finishReason === 'RECITATION') {
          text = "I'm sorry, I cannot respond as this would involve reciting copyrighted content.";
        }
      } else {
        text = "No response generated by the model.";
      }
    } catch (e) {
      // Fallback to text() but catch potential errors
      try {
        text = result.response.text();
      } catch (inner) {
        text = "Failed to extract text from model response.";
      }
    }

    let toolCalls = undefined;
    try {
      const responseTools = result.response.functionCalls();
      if (responseTools && responseTools.length > 0) {
        toolCalls = responseTools;
      }
    } catch (e) {
      // Function calls might not be present
    }

    return {
      content: text,
      toolCalls,
    };
  }
}
